POST http://localhost:8080/api/pizzas
Content-Type: application/x-www-form-urlencoded

name=kaaaaapricioza&description=(sunka, kecap, kaskaval)&veggie= &ingredientList=cheder,ham

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
  client.assert(response.headers.valueOf("Location")!= null, "Invalid Location");
  client.assert(response.body.hasOwnProperty("slotId"), 'Can not find the slotId');
  client.global.set("newSlotUrl", response.headers.valueOf("Location"));
  client.global.set("slotId", response.body["slotId"]);
});
%}


###
PATCH http://localhost:8080/api/pizzas/kapricioza
Content-Type: application/x-www-form-urlencoded

name=kapricioza&description=(ham, kecap, peperoni)&veggie=true&ingredientList=cheder

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 201");
  client.assert(response.body.hasOwnProperty("slotId"), 'Can not find the slotId');
});
%}


###
DELETE http://localhost:8080/api/pizzas/kkkapricioza

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET http://localhost:8080/api/pizzas

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET http://localhost:8080/api/pizzas/Burger Classic

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET http://localhost:8080/api/pizzas/less?totalIngredients=3

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET http://localhost:8080/api/pizzas/compare?pizza1=Burger Barbecue&pizza2=Margherita

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET http://localhost:8080/api/ingredients/all

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET http://localhost:8080/api/ingredients/cheder/pizzas

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
